# This file was generated by GoReleaser. DO NOT EDIT.
cask "tapd" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d2d5ab7f30a38bee204388068a820b11c271bc5744eae7cf3b61496e76530650"
      url "https://github.com/go-tapd/cli/releases/download/v#{version}/tapd_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d3c88f1ca0eb5888901ab86000358622f7fccfae24b67185e252d5441c164f54"
      url "https://github.com/go-tapd/cli/releases/download/v#{version}/tapd_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54d5c25a3779b95e597890d0084776bc6521595e7179ac185587f5ca05ce3b7d"
      url "https://github.com/go-tapd/cli/releases/download/v#{version}/tapd_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "275ea6034769386f5db4ee74fb588d33b56bf03f27acf6dec79c0a3dac73b4c0"
      url "https://github.com/go-tapd/cli/releases/download/v#{version}/tapd_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "tapd"
  desc "TAPD command line client"
  homepage "https://github.com/go-tapd/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tapd"

  # No zap stanza required

end
