# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapd < Formula
  desc "TAPD command line client"
  homepage "https://github.com/go-tapd/cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.7/tapd_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "052b3d9301663a8b70d31e17953a6d5880e61f6e8559c5f0a104b205acec8a4f"

      define_method(:install) do
        bin.install "tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.7/tapd_0.1.7_Darwin_arm64.tar.gz"
      sha256 "c8efe413842a5208917fa79dfce0241c371f63d0f9eff53998b65dda690eae1e"

      define_method(:install) do
        bin.install "tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.7/tapd_0.1.7_Linux_x86_64.tar.gz"
      sha256 "f3c929a992de220ba3b7a22d5da1d1a76ba9fa2e176deca1e19366eaa63f8307"
      define_method(:install) do
        bin.install "tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.7/tapd_0.1.7_Linux_arm64.tar.gz"
      sha256 "50f289bbe403f958963ca685be37c5c02dbd5c754304c8878771870c7a7f551d"
      define_method(:install) do
        bin.install "tapd"
      end
    end
  end

  test do
    system "#{bin}/tapd", "--help"
  end
end
