# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapd < Formula
  desc "TAPD command line client"
  homepage "https://github.com/go-tapd/cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.4/tapd_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "5e80580a045ecfedb695f8f55e390e569da829624c5e37ed5aae647551b8980e"

      define_method(:install) do
        bin.install "tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.4/tapd_0.1.4_Darwin_arm64.tar.gz"
      sha256 "23629027730b23c1ecc66f0a1da9bee7cc3acf4ac3647806c513e611e5c5d612"

      define_method(:install) do
        bin.install "tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.4/tapd_0.1.4_Linux_x86_64.tar.gz"
      sha256 "9a5c2719b7f26aec769489fb43f6332e4a226c4240e6d59c43b44b2ded2731dd"
      define_method(:install) do
        bin.install "tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-tapd/cli/releases/download/v0.1.4/tapd_0.1.4_Linux_arm64.tar.gz"
      sha256 "0d3ac03f8476ce75876a25efe6289330c50cf967d4942f10855f154f0095cfff"
      define_method(:install) do
        bin.install "tapd"
      end
    end
  end

  test do
    system "#{bin}/tapd", "--help"
  end
end
